[package]
name = "music"
version = "0.1.0"
authors = ["Thaynã B. Moretti <moretty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.15.0"
strum_macros = "0.15.0"
